### ISSUE TITLE
Add info on built-in methods to README

### ISSUE THREAD

**Issue by JasonBarnabe** [patmaddox/no-peeping-toms#29]
Upon updating my app that uses no_peeping_toms to Rails 5.1, I ran into this error:

```
  Cannot define multiple 'included' blocks for a Concern
# /Users/jason/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.4/lib/active_support/concern.rb:126:in `included'
# /Users/jason/.rvm/gems/ruby-2.3.3/gems/no_peeping_toms-2.1.3/lib/no_peeping_toms.rb:8:in `<module:NoPeepingToms>'
# /Users/jason/.rvm/gems/ruby-2.3.3/gems/no_peeping_toms-2.1.3/lib/no_peeping_toms.rb:5:in `<top (required)>'
```
After doing some research, I found that the methods that I have been using have been available in Rails/rails-observers [since Rails 3.1](https://apidock.com/rails/v3.1.0/ActiveModel/ObserverArray/disable).

Please include a note in the README that this gem is unnecessary for Rails 3.1 and above.

**Comment by patmaddox** [comment]
Done! Thanks
